name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Install Dioxus-CLI
        shell: bash
        run: cargo install dioxus-cli

      - name: Build Project 🎁
        shell: bash
        run: dx build --bin www --release && cp ./www/dist/index.html ./www/dist/404.html

      - name: Deploy Project 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./www/dist
