name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build Project 🎁
        shell: bash
        run: wasm-pack build unlox-wasm --target web --out-dir ../www/pkg && cd www && npm install && npm run build 

      - name: Deploy Project 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./www/dist
